In [1]:
# https://huggingface.co/jinaai/jina-colbert-v1-en
# Load model directly
from transformers import AutoTokenizer, HF_ColBERT

tokenizer = AutoTokenizer.from_pretrained("jinaai/jina-colbert-v1-en", trust_remote_code=True)
model = HF_ColBERT.from_pretrained("jinaai/jina-colbert-v1-en", trust_remote_code=True)

ImportError: cannot import name 'HF_ColBERT' from 'transformers' (/Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/transformers/__init__.py)

# BAAI/bge-reranker-large
https://huggingface.co/BAAI/bge-reranker-large?library=true

In [3]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification
  
model = AutoModelForSequenceClassification.from_pretrained("BAAI/bge-reranker-large")

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/801 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

In [5]:
from FlagEmbedding import FlagModel
sentences_1 = ["样例数据-1", "样例数据-2"]
sentences_2 = ["样例数据-3", "样例数据-4"]
model = FlagModel('BAAI/bge-large-zh-v1.5', 
                  query_instruction_for_retrieval="为这个句子生成表示以用于检索相关文章：",
                  use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation
embeddings_1 = model.encode(sentences_1)
embeddings_2 = model.encode(sentences_2)
similarity = embeddings_1 @ embeddings_2.T
print(similarity)

# for s2p(short query to long passage) retrieval task, suggest to use encode_queries() which will automatically add the instruction to each query
# corpus in retrieval task can still use encode() or encode_corpus(), since they don't need instruction
queries = ['query_1', 'query_2']
passages = ["样例文档-1", "样例文档-2"]
q_embeddings = model.encode_queries(queries)
p_embeddings = model.encode(passages)
scores = q_embeddings @ p_embeddings.T


tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/110k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/439k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.30G [00:00<?, ?B/s]

[[0.855  0.8525]
 [0.874  0.856 ]]


In [6]:
scores

array([[0.3372, 0.2048],
       [0.226 , 0.3848]], dtype=float16)

In [7]:
# https://huggingface.co/BAAI/bge-reranker-large?library=true
from sentence_transformers import SentenceTransformer
queries = ['query_1', 'query_2']
passages = ["样例文档-1", "样例文档-2"]
instruction = "为这个句子生成表示以用于检索相关文章：" # Generate a representation of this sentence for use in retrieving relevant articles

model = SentenceTransformer('BAAI/bge-large-zh-v1.5')
q_embeddings = model.encode([instruction+q for q in queries], normalize_embeddings=True)
p_embeddings = model.encode(passages, normalize_embeddings=True)
scores = q_embeddings @ p_embeddings.T


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/30.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [5]:
from FlagEmbedding import FlagModel
sentences_1 = ["Sample data-1", "Sample data-2"]
sentences_2 = ["Sample data-3", "Sample data-4"]
model = FlagModel('BAAI/bge-large-en-v1.5', 
                  query_instruction_for_retrieval="Represent this sentence for searching relevant passages: ",
                  use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation
embeddings_1 = model.encode(sentences_1)
embeddings_2 = model.encode(sentences_2)
similarity = embeddings_1 @ embeddings_2.T
print(similarity)

# for s2p (short query to long passage) retrieval task, suggest to use encode_queries() which will automatically add the instruction to each query
# corpus in retrieval task can still use encode() or encode_corpus(), since they don't need instruction
queries = ['query_1', 'query_2']
passages = ["Sample document-1", "Sample document-2"]
q_embeddings = model.encode_queries(queries)
p_embeddings = model.encode(passages)
scores = q_embeddings @ p_embeddings.T


tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

[[0.8755 0.8794]
 [0.8716 0.8677]]


## Re-ranking BGE small
https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/reranker

In [7]:
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-reranker-large')
model = AutoModelForSequenceClassification.from_pretrained('BAAI/bge-reranker-large')
model.eval()

pairs = [['what is panda?', 'hi'], ['what is panda?', 'The giant panda (Ailuropoda melanoleuca), sometimes called a panda bear or simply panda, is a bear species endemic to China.']]
with torch.no_grad():
    inputs = tokenizer(pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
    scores = model(**inputs, return_dict=True).logits.view(-1, ).float()
    print(scores)

tensor([-5.6085,  5.7623])


In [7]:
# make new db
from CreateDocuments import create_chunks
import RAG_utils
%load_ext autoreload
%autoreload 2

# chunks_file_path = create_chunks(1000, 200, 'rag-dataset-12000/data/train-00000-of-00001-9df3a936e1f63191.parquet')
# dataset = 'rag-dataset-12000'

collection_name = 'chroma_' + dataset + '_' + str(1000) + '_' + str(200) + '_' + 'all-MiniLM-L6-v2'
vs = RAG_utils.create_chroma_db(chunks_file_path, collection_name)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
here


In [8]:
vs



Collection(name=chroma_rag-dataset-12000_1000_200_all-MiniLM-L6-v2)

In [ ]:
import RAG_utils
%load_ext autoreload
%autoreload 2
# db = RAG_utils.access_chroma_db(collection_name='train_1000_200_all-MiniLM-L6-v2')
create_chroma_db 

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


NameError: name 'create_chroma_db' is not defined

In [65]:
from utils.db.es import search_data, search_vector
index_name = 'rag-dataset-12000-train'
k = 2
question = 'What does the name Madigan mean in Irish?'
contexts = [context['_source']['sentence'] for context in search_data(question, index_name, k)]
contexts

['What in heaven’s name does that mean?',
 'Madigan means “small dog” in Irish.']

In [75]:
from utils.db.es import search_data, search_vector
index_name = 'rag-dataset-12000-train-vector'
k = 5
question = 'What does the name Madigan mean in Irish?'
contexts = [context['_source']['sentence'] for context in search_vector(question, index_name, k)]
contexts[1]

'Challenge 10: Write a Story From a Movie You Like Hey, Everybody! Sorry it’s been so long. I’ve been working on this How To Train Your Dragon story a lot. […]\nChallenge 4: Have two of your book characters from different book worlds meet. Write a short story about it. Writefury’s Characters Gilligan: From my first book: “Odd Team Out”. He […]\nThought I’d add a little bit of Riley Trivia this time. Madigan means “small dog” in Irish. Magnus means “big” in latin. Chapter 6 Training Shyloh After her […]\nCHAPTER 4 Not a Slave A few days later, all the Irish had been sold. Riley had been sold to a cranky old lady named Freyda. In Freyda’s house, Riley […]\nCHAPTER 2 Captured Riley opened her eyes and stared upward. Two seagulls squawked overhead. The ground rocked underneath her. She sat up slowly, her head throbbing. Maddy barked happily, Riley […]'

In [76]:
es_doc = contexts[1]

In [85]:
question = 'What does the name Madigan mean in Irish?'

system_message = """You are a helpful assistant. Answer the user's question in one sentence based on the provided context. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information. Do NOT start your response with "According to the provided context." """
user_message_template = """Context: {context} Question: {question}"""
# db.__query_collection
# documents = db.similarity_search(question, k=11)
documents = [doc[0] for doc in db.similarity_search_with_score(question, k=11)]
documents2 = [doc for doc in db.similarity_search(question, k=11)]

assert [doc.page_content for doc in documents] == [doc.page_content for doc in documents2]
# documents = db._collection.query(
#     query_texts=question,
#     n_results=5,
#     include=["embeddings", "documents", "metadatas", "distances"],
# )
context = RAG_utils.format_docs([doc for doc in documents])
user_message = user_message_template.format(context=context, question=question)

answer = RAG_utils.gen_text_ollama(sys_msg=system_message, user_msg=user_message,options={'seed':0, 'temperature':0.01})
print(question)
print(answer)
print(documents[0])
if 'madigan' in context.lower():
    print('=' * 10, 'madigan in context')
    for i, doc in enumerate(documents):
        if 'madigan' in doc.page_content.lower():
            print(i)
            print(doc)
            break

What does the name Madigan mean in Irish?
The primary identifier of a family is its "name." The patronymic of a family is the "name" derived from the father, which generally becomes the surname of any of the family's children.
page_content='edit* my ancestors were from Clan Ross\nFamily lore is that we were MacDonalds in Scotland, but chased out. Many family members moved to York and took the name Sturdy.'
========== madigan in context
1
page_content='Challenge 10: Write a Story From a Movie You Like Hey, Everybody! Sorry it’s been so long. I’ve been working on this How To Train Your Dragon story a lot. […]\nChallenge 4: Have two of your book characters from different book worlds meet. Write a short story about it. Writefury’s Characters Gilligan: From my first book: “Odd Team Out”. He […]\nThought I’d add a little bit of Riley Trivia this time. Madigan means “small dog” in Irish. Magnus means “big” in latin. Chapter 6 Training Shyloh After her […]\nCHAPTER 4 Not a Slave A few days lat

In [80]:
documents[1].page_content == es_doc

True

In [37]:
documents

[(Document(page_content='edit* my ancestors were from Clan Ross\nFamily lore is that we were MacDonalds in Scotland, but chased out. Many family members moved to York and took the name Sturdy.'),
  0.21601745142327888),
 (Document(page_content='Looking to the future, a resurgence in the popularity of traditional Scottish forenames in recent years is likely to combat Anglicisation, said Hough.\n“Far more Gaelic and Celtic-derived personal names are being chosen by parents in Scotland, which can be a way of affirming national identity,” she says. “Gaelic-derived forenames that are in the top 100 names in Scotland at the moment include Aiden, Callum and Finlay. Cameron is originally a clan name, and Lewis, Evan and Isla are all place names.”\nYou can view a map of Scotland’s most popular surnames at Tartan Footprint.Tagged\nMy father is a Ross. How can I find out about our ancestors\nMy father is a Simpson from Frazer clan. How can I find out about our ancestors?\naccording to my grand mo

In [38]:
if 'madigan' in context.lower():
    print('madigan' in context.lower())
    print(context)

In [ ]:
# from colbert.modeling.checkpoint import Checkpoint
# from colbert.infra import ColBERTConfig

# query = ["How to use ColBERT for indexing long documents?"]
# documents = [
#     "ColBERT is an efficient and effective passage retrieval model.",
#     "Jina-ColBERT is a ColBERT-style model but based on JinaBERT so it can support both 8k context length.",
#     "JinaBERT is a BERT architecture that supports the symmetric bidirectional variant of ALiBi to allow longer sequence length.",
#     "Jina-ColBERT model is trained on MSMARCO passage ranking dataset, following a very similar training procedure with ColBERTv2.",
# ]

# config = ColBERTConfig(query_maxlen=32, doc_maxlen=512)
# ckpt = Checkpoint(args.reranker, colbert_config=colbert_config)
# Q = ckpt.queryFromText([all_queries[i]])
# D = ckpt.docFromText(all_passages, bsize=32)[0]
# D_mask = torch.ones(D.shape[:2], dtype=torch.long)
# scores = colbert_score(Q, D, D_mask).flatten().cpu().numpy().tolist()
# ranking = numpy.argsort(scores)[::-1]
# print(ranking)


## Jina


In [4]:
from colbert.modeling.checkpoint import Checkpoint
from colbert.infra import ColBERTConfig
import torch
from colbert.modeling.colbert import colbert_score
import numpy as np

query = ["How to use ColBERT for indexing long documents?"]
documents = [
    "ColBERT is an efficient and effective passage retrieval model.",
    "Jina-ColBERT is a ColBERT-style model but based on JinaBERT so it can support both 8k context length.",
    "JinaBERT is a BERT architecture that supports the symmetric bidirectional variant of ALiBi to allow longer sequence length.",
    "Jina-ColBERT model is trained on MSMARCO passage ranking dataset, following a very similar training procedure with ColBERTv2.",
]

config = ColBERTConfig(query_maxlen=32, doc_maxlen=512)
ckpt = Checkpoint("colbert-ir/colbertv2.0", colbert_config=ColBERTConfig(root="experiments"))
Q = ckpt.queryFromText(query)
D = ckpt.docFromText(documents, bsize=32)[0]
D_mask = torch.ones(D.shape[:2], dtype=torch.long)
scores = colbert_score(Q, D, D_mask).flatten().cpu().numpy().tolist()
ranking = np.argsort(scores)[::-1]
print(ranking)


artifact.metadata:   0%|          | 0.00/1.63k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/405 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

[May 18, 17:37:24] Loading segmented_maxsim_cpp extension (set COLBERT_LOAD_TORCH_EXTENSION_VERBOSE=True for more info)...


RuntimeError: Error building extension 'segmented_maxsim_cpp': [1/2] c++ -MMD -MF segmented_maxsim.o.d -DTORCH_EXTENSION_NAME=segmented_maxsim_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/TH -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/THC -isystem /Users/ryankish/miniforge3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -c '/Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/colbert/modeling/segmented_maxsim.cpp' -o segmented_maxsim.o 
FAILED: segmented_maxsim.o 
c++ -MMD -MF segmented_maxsim.o.d -DTORCH_EXTENSION_NAME=segmented_maxsim_cpp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/TH -isystem /Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/THC -isystem /Users/ryankish/miniforge3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -c '/Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/colbert/modeling/segmented_maxsim.cpp' -o segmented_maxsim.o 
clang: error: no such file or directory: '490'
clang: error: no such file or directory: 'Practicum'
clang: error: no such file or directory: 'in'
clang: error: no such file or directory: 'Intelligent'
clang: error: no such file or directory: 'Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include'
clang: error: no such file or directory: '490'
clang: error: no such file or directory: 'Practicum'
clang: error: no such file or directory: 'in'
clang: error: no such file or directory: 'Intelligent'
clang: error: no such file or directory: 'Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include'
clang: error: no such file or directory: '490'
clang: error: no such file or directory: 'Practicum'
clang: error: no such file or directory: 'in'
clang: error: no such file or directory: 'Intelligent'
clang: error: no such file or directory: 'Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/TH'
clang: error: no such file or directory: '490'
clang: error: no such file or directory: 'Practicum'
clang: error: no such file or directory: 'in'
clang: error: no such file or directory: 'Intelligent'
clang: error: no such file or directory: 'Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/torch/include/THC'
ninja: build stopped: subcommand failed.
