In [2]:
# https://huggingface.co/jinaai/jina-colbert-v1-en
# Load model directly
from transformers import AutoTokenizer, HF_ColBERT

tokenizer = AutoTokenizer.from_pretrained("jinaai/jina-colbert-v1-en", trust_remote_code=True)
model = HF_ColBERT.from_pretrained("jinaai/jina-colbert-v1-en", trust_remote_code=True)

ImportError: cannot import name 'HF_ColBERT' from 'transformers' (/Users/ryankish/Documents/Northwestern/Curriculum/Spring/MSAI 490 Practicum in Intelligent Systems/advanced_rag_team_twain/ragenv/lib/python3.9/site-packages/transformers/__init__.py)

# BAAI/bge-reranker-large
https://huggingface.co/BAAI/bge-reranker-large?library=true

In [3]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification
  
model = AutoModelForSequenceClassification.from_pretrained("BAAI/bge-reranker-large")

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/801 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

In [5]:
from FlagEmbedding import FlagModel
sentences_1 = ["样例数据-1", "样例数据-2"]
sentences_2 = ["样例数据-3", "样例数据-4"]
model = FlagModel('BAAI/bge-large-zh-v1.5', 
                  query_instruction_for_retrieval="为这个句子生成表示以用于检索相关文章：",
                  use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation
embeddings_1 = model.encode(sentences_1)
embeddings_2 = model.encode(sentences_2)
similarity = embeddings_1 @ embeddings_2.T
print(similarity)

# for s2p(short query to long passage) retrieval task, suggest to use encode_queries() which will automatically add the instruction to each query
# corpus in retrieval task can still use encode() or encode_corpus(), since they don't need instruction
queries = ['query_1', 'query_2']
passages = ["样例文档-1", "样例文档-2"]
q_embeddings = model.encode_queries(queries)
p_embeddings = model.encode(passages)
scores = q_embeddings @ p_embeddings.T


tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/110k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/439k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.30G [00:00<?, ?B/s]

[[0.855  0.8525]
 [0.874  0.856 ]]


In [6]:
scores

array([[0.3372, 0.2048],
       [0.226 , 0.3848]], dtype=float16)

In [7]:
# https://huggingface.co/BAAI/bge-reranker-large?library=true
from sentence_transformers import SentenceTransformer
queries = ['query_1', 'query_2']
passages = ["样例文档-1", "样例文档-2"]
instruction = "为这个句子生成表示以用于检索相关文章：" # Generate a representation of this sentence for use in retrieving relevant articles

model = SentenceTransformer('BAAI/bge-large-zh-v1.5')
q_embeddings = model.encode([instruction+q for q in queries], normalize_embeddings=True)
p_embeddings = model.encode(passages, normalize_embeddings=True)
scores = q_embeddings @ p_embeddings.T


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/30.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [8]:
scores

array([[0.33725047, 0.20507805],
       [0.22591078, 0.38495797]], dtype=float32)

In [ ]:
# from colbert.modeling.checkpoint import Checkpoint
# from colbert.infra import ColBERTConfig

# query = ["How to use ColBERT for indexing long documents?"]
# documents = [
#     "ColBERT is an efficient and effective passage retrieval model.",
#     "Jina-ColBERT is a ColBERT-style model but based on JinaBERT so it can support both 8k context length.",
#     "JinaBERT is a BERT architecture that supports the symmetric bidirectional variant of ALiBi to allow longer sequence length.",
#     "Jina-ColBERT model is trained on MSMARCO passage ranking dataset, following a very similar training procedure with ColBERTv2.",
# ]

# config = ColBERTConfig(query_maxlen=32, doc_maxlen=512)
# ckpt = Checkpoint(args.reranker, colbert_config=colbert_config)
# Q = ckpt.queryFromText([all_queries[i]])
# D = ckpt.docFromText(all_passages, bsize=32)[0]
# D_mask = torch.ones(D.shape[:2], dtype=torch.long)
# scores = colbert_score(Q, D, D_mask).flatten().cpu().numpy().tolist()
# ranking = numpy.argsort(scores)[::-1]
# print(ranking)
